# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCompromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(choices=[('PRIVADA', 'PRIVADA'), ('PUBLICA', 'PUBLICA')], max_length=7),
        ),
        migrations.AddField(
            model_name='agendacompromisso',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
        migrations.AddField(
            model_name='agendacompromisso',
            name='compromisso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromisso'),
        ),
    ]
