# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170918_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendacompromisso',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='agendacompromisso',
            name='compromisso',
        ),
        migrations.AddField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(null=True, to='agenda.Compromisso'),
        ),
        migrations.DeleteModel(
            name='AgendaCompromisso',
        ),
    ]
