# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170918_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(to='agenda.Compromisso'),
        ),
    ]
