# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170918_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(to='agenda.Compromisso', verbose_name='compromissos'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='feriados',
            field=models.ManyToManyField(to='agenda.Feriado', verbose_name='feriados'),
        ),
    ]
