# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20170918_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feriado',
        ),
        migrations.AlterField(
            model_name='agendainstitucional',
            name='feriados',
            field=models.ManyToManyField(to='agenda.Compromisso', verbose_name='feriados'),
        ),
    ]
