# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170918_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendainstitucional',
            name='feriados',
        ),
        migrations.AddField(
            model_name='agenda',
            name='institucional',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AgendaInstitucional',
        ),
    ]
