# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20170925_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(choices=[('PUBLICA', 'PUBLICA'), ('PRIVADA', 'PRIVADA')], max_length=7),
        ),
    ]
