# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20170925_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='compromissos',
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='data',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='dhfim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='dhinicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
