# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='permitidos',
            field=models.ManyToManyField(null=True, related_name='usuariospermitidosveragenda', to='agenda.Usuario'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='convidados',
            field=models.ManyToManyField(null=True, related_name='usuariosconvidadosparacompromisso', to='agenda.Usuario'),
        ),
    ]
