# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20170925_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='compromisso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compromisso', to='agenda.Compromisso'),
        ),
    ]
