# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_remove_agenda_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='permitidos',
            field=models.ManyToManyField(null=True, related_name='usuariospermitidosveragenda', to='agenda.Usuario'),
        ),
    ]
