# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_agenda_permitidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='usuario',
        ),
    ]
