# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_remove_agenda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
